name: "Server deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY_GITHUB }}
          debug: true
          script: |
            echo "ğŸš€ Loyihani tayyorlash boshlanmoqda..."

            mkdir -p /home/${{ secrets.SSH_USER }}/Azizbek_5-oy_imtihon
            cd /home/${{ secrets.SSH_USER }}/Azizbek_5-oy_imtihon

            if [ ! -d "start-up" ]; then
              echo "ğŸ“¥ Git repozitoriyasini klonlash..."
              git clone https://github.com/Bobur815/Azizbek_imtihon.git
            fi

            echo "ğŸ”„ Repozitoriyani yangilash..."
            cd start-up
            git pull origin main


            echo "ğŸ§¹ Docker konteynerlar va volume tozalanmoqda..."
            docker compose down -v

            echo "ğŸ—ï¸ Docker image'lar --no-cache bilan qayta build qilinmoqda..."
            docker compose build --no-cache

            echo "ğŸ”¥ Docker konteynerlar ishga tushirilmoqda..."
            docker compose up -d

            echo "ğŸ“œ Loglar: "
            docker compose logs --tail=100
            echo "âœ… Deploy muvaffaqiyatli yakunlandi!"
