name: "Server deploy"

on:
  push:
    branch:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout code
      uses: actions/Checkout@v3

    - name: Deploy over SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.DB_HOST }}
        username: ${{ secrets.DB_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "ğŸš€ Loyihani tayyorlash boshlanmoqda..."
          echo "ğŸ“ Loyihani joylash..."
          mkdir -p /home/ubuntu/up
          cd /home/ubuntu/up

          if [ ! -d ".git" ]; then
            echo "ğŸ“¥ Git repozitoriyasini klonlash..."
            git clone https://github.com/aziz-davronov107/start-up
          else
            echo "ğŸ”„ Repozitoriyani yangilash..."
            cd up
            git pull origin main
          fi
          

          if [ ! -f ".env" ]; then
            echo "ğŸ“„ .env fayl yaratilmoqda..."
            echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
          else
            echo "âœ… .env fayl mavjud, yangilanmaydi."
          fi

          echo "ğŸ§¹ Docker konteynerlar toâ€˜xtatilmoqda..."
          docker-compose down

          echo "ğŸ—ï¸ Docker image'lar qayta build qilinmoqda..."
          docker-compose build --no-cache

          echo "ğŸ”¥ Docker konteynerlar ishga tushirilmoqda..."
          docker-compose up -d

          echo "âœ… Deploy muvaffaqiyatli yakunlandi!"
