name: "Server deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DB_HOST }}
          username: ${{ secrets.DB_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "ğŸš€ Loyihani tayyorlash boshlanmoqda..."
            

            cd /home/ubuntu/

            if [ ! -d "start-up" ]; then
              echo "ğŸ“¥ Git repozitoriyasini klonlash..."
              git clone https://github.com/aziz-davronov107/start-up.git
            fi
            
            echo "ğŸ”„ Repozitoriyani yangilash..."
            cd start-up
            git pull origin main

            echo "ğŸ“„ .env faylni yozib olish..."
            echo "${{ secrets.ENV_FILE }}" > .env

            echo "ğŸ§¹ Docker konteynerlar toâ€˜xtatilmoqda..."
            docker-compose down

            echo "ğŸ—ï¸ Docker image'lar qayta build qilinmoqda..."
            docker-compose build

            echo "ğŸ”¥ Docker konteynerlar ishga tushirilmoqda..."
            docker-compose up -d

            echo "âœ… Deploy muvaffaqiyatli yakunlandi!"
