name: "Server deploy"

on:
  push:
    branch:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout code
      uses: actions/Checkout@v3

    - name: Deploy over SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{secrets.DB_HOST}}
        username: ${{secrets.DB_USER}}
        key: ${{secrets.SSH_KEY}}
        script: |
          echo "ğŸš€ Loyihani tayyorlash boshlanmoqda..."

          # Docker oâ€˜rnatilganligini tekshirish
          if ! [ -x "$(command -v docker)" ]; then
            echo "ğŸ³ Docker oâ€˜rnatilmayapti, oâ€˜rnatilmoqda..."
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            sudo usermod -aG docker $USER
          else
            echo "âœ… Docker allaqachon oâ€˜rnatilgan."
          fi

          # Docker Compose oâ€˜rnatilganligini tekshirish
          if ! [ -x "$(command -v docker-compose)" ]; then
            echo "ğŸ“¦ Docker Compose oâ€˜rnatilmayapti, oâ€˜rnatilmoqda..."
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          else
            echo "âœ… Docker Compose allaqachon oâ€˜rnatilgan."
          fi

          echo "ğŸ“ Loyihani joylash..."
          mkdir -p /home/ubuntu/new
          cd /home/ubuntu/new

          if [ ! -d ".git" ]; then
            echo "ğŸ“¥ Git repozitoriyasini klonlash..."
            git clone https://github.com/aziz-davronov107/CI-CD.git .
          else
            echo "ğŸ”„ Repozitoriyani yangilash..."
            git pull origin main
          fi
          if [! -f ".env" ]; then
            echo "ğŸ“„ .env fayl yaratilmoqda..."
            echo "${{secrets.ENV_FILE_CONTENT}}" > .env
          else
            echo "âœ… .env fayl mavjud, yangilanmaydi."
          fi
          echo "ğŸ§¹ Docker konteynerlar toâ€˜xtatilmoqda..."
          docker-compose down

          echo "ğŸ—ï¸ Docker image'lar qayta build qilinmoqda..."
          docker-compose build --no-cache

          echo "ğŸ”¥ Docker konteynerlar ishga tushirilmoqda..."
          docker-compose up -d

          echo "âœ… Deploy muvaffaqiyatli yakunlandi!"
